---
title: "Design and analysis template: MCP-Mod with multiple regimen"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = TRUE)
```

This is a more extensive example and covers both design and analysis stage.

Utilize LIK weight-loss example
https://clinicaltrials.gov/ct2/show/results/NCT03100058

# Design stage


```{r}
library(DoseFinding)
dosesQD <- c(2.5, 10, 50, 150)
dosesBID <- c(2.5, 5, 25, 50)

modsQD <- Mods(emax = c(5, 50),
               sigEmax = rbind(c(75,3.5), c(25, 0.7)),
               maxEff = -1,
               doses=c(0, dosesQD))
modsBID <- Mods(emax = c(5, 50),
                sigEmax = c(75, 3.2),
                maxEff = -1,
                doses=c(0, 2*dosesBID)
plot(modsQD, superpose=TRUE)
plot(modsBID, superpose=TRUE)
## calculate optimal contrasts
indQD <- c(1:5)
indBID <- c(1,6,7,8,9)
CQD <- optContr(modsQD, S=V[indQD,indQD])$contMat
rownames(CQD)[2:5] <- paste(rownames(CQD)[2:5], "QD", sep="-")
colnames(CQD) <- paste(colnames(CQD), "QD", sep="-")

CBID <- optContr(modsBID, S=V[indBID,indBID])$contMat
rownames(CBID)[2:5] <- paste(rownames(CBID)[2:5], "BID", sep="-")
colnames(CBID) <- paste(colnames(CBID), "BID", sep="-")

## create combined matrix
cMat <- rbind(
  c(CQD[1,], CBID[1,]),
  cbind(CQD[-1,],0,0,0,0,0,0),
  cbind(0,0,0,0,0,0,CBID[-1,])
)

```

Analysis using generalized approach

```{r}

MCT <- function(est, S, contMat, df){
  ct <- as.vector(est %*% contMat)
  covMat <- t(contMat) %*% S %*% contMat
  den <- sqrt(diag(covMat))
  tStat <- ct/den
  corMat <- cov2cor(covMat)
  pVals <- DoseFinding:::pValues(contMat, corMat, NA, df, tStat, "one.sided", 
                                 mvtnorm.control())
  res <- list(contMat = contMat, corMat = corMat, tStat = tStat,
              pVals=pVals,
              alternative = "one.sided")
  res
}

MCT(mn, V, cMat, df=447)
```

# Analysis stage: Dose-response modelling
