---
title: "Design and analysis template: MCP-Mod with multiple regimen"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = TRUE)
```

This is a more extensive example and covers both design and analysis stage.

Utilize LIK weight-loss example
https://clinicaltrials.gov/ct2/show/results/NCT03100058

# Design stage


```{r}
library(DoseFinding)
doses <- c(0, 12.5, 25, 50, 100)
## define candidate models (as used in NVA study)
mods <- Mods(emax = c(2.6, 12.5), 
             sigEmax = c(30.5, 3.5),
             quadratic = -0.00776,
             placEff = 1.25, maxEff = 0.15,
         doses = doses)
## graphical display of candidate shapes
plot(mods)
```

```{r}
## optimal contrasts
contMat <- optContr(mods, w=1)
pows <- powN(upperN = 100, lowerN=10, step = 10,  
             contMat = contMat,sigma = 0.34,  
             altModels = mods, alpha = 0.05, 
             alRatio = rep(1, 5))
plot(pows)
## wrapper function sampSize performs sample-size calculations
sampSizeMCT(upperN=100, contMat = contMat, sigma = 
            0.34, altModels=mods, power = 0.9, 
alRatio = rep(1, 5), alpha = 0.05, sumFct = mean)
```

# Analysis stage: Contrast test


```{r}
  ## perform the test
  
  ## #	Candidate models for qd regimen	        Candidate models for bid regimen
  ## 1	Emax model: ED50 = 5 mg	                Emax model: ED50 = 5 mg
  ## 2	Emax model: ED50 = 50 mg         	Emax model: ED50 = 50 mg
  ## 3	Sigmoid Emax: ED50 = 75 mg, H = 3.5	Sigmoid Emax: ED50 = 75 mg, H = 3.2
  ## 4	Sigmoid Emax: ED50 = 25 mg, H = 0.7	Linear log-dose: null, c = 0.8
  ## 5	β-model: α = 0.8, β = 0.2, scale = 180	Linear
  ## 6	Exponential: λ = 125	                Quadratic: δ = -0.007
  ## models formulated on total daily dose
  modsQD <- Mods(emax = c(5, 50),
                 sigEmax = rbind(c(75,3.5), c(25, 0.7)),
                 betaMod = c(0.8, 0.2),
                 exponential = 125,
                 maxEff = -1,
                 addArgs=list(scal=180),
                 doses=c(0,2.5,10,50,150))
  modsBID <- Mods(emax = c(5, 50),
                sigEmax = c(75, 3.2),
                linlog = NULL,
                linear = NULL,
                quadratic = -0.007,
                maxEff = -1,
                addArgs=list(off=0.8), 
                doses=c(0,5,10,50,100))
  ## plot(modsQD, superpose=TRUE)
  ## plot(modsBID, superpose=TRUE)
  
  ## calculate optimal contrasts
  indQD <- c(1:5)
  indBID <- c(1,6,7,8,9)
  CQD <- optContr(modsQD, S=V[indQD,indQD])$contMat
  rownames(CQD)[2:5] <- paste(rownames(CQD)[2:5], "QD", sep="-")
  colnames(CQD) <- paste(colnames(CQD), "QD", sep="-")
  
  CBID <- optContr(modsBID, S=V[indBID,indBID])$contMat
  rownames(CBID)[2:5] <- paste(rownames(CBID)[2:5], "BID", sep="-")
  colnames(CBID) <- paste(colnames(CBID), "BID", sep="-")
  
  ## create combined matrix
  cMat <- rbind(
    c(CQD[1,], CBID[1,]),
    cbind(CQD[-1,],0,0,0,0,0,0),
    cbind(0,0,0,0,0,0,CBID[-1,])
  )
  
  MCT <- function(est, S, contMat, df){
    ct <- as.vector(est %*% contMat)
    covMat <- t(contMat) %*% S %*% contMat
    den <- sqrt(diag(covMat))
    tStat <- ct/den
    corMat <- cov2cor(covMat)
    pVals <- DoseFinding:::pValues(contMat, corMat, NA, df, tStat, "one.sided", 
                                   mvtnorm.control())
    res <- list(contMat = contMat, corMat = corMat, tStat = tStat,
                pVals=pVals,
                alternative = "one.sided")
    res
  }
  
  MCT(mn, V, cMat, df=447)
```

# Analysis stage: Dose-response modelling
